CREATE TABLE Stasjon (
    navn TEXT PRIMARY KEY NOT NULL,
    moh REAL
);

CREATE TABLE Banestrekning (
    strekningID INTEGER NOT NULL,
    navn TEXT,
    energiType TEXT,
    start TEXT,
    ende TEXT,
    PRIMARY KEY (strekningID AUTOINCREMENT),
    FOREIGN KEY (start) REFERENCES Stasjon(navn) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (ende) REFERENCES Stasjon(navn) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Delstrekning (
    stasjonA TEXT NOT NULL,
    stasjonB TEXT NOT NULL,
    distanse REAL,
    dobbeltSpor BOOLEAN,
    strekningID INTEGER,
    PRIMARY KEY (stasjonA, stasjonB),
    FOREIGN KEY (stasjonA) REFERENCES Stasjon(navn) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (stasjonB) REFERENCES Stasjon(navn) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (strekningID) REFERENCES Banestrekning(strekningID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Operatør (
    operatørID INTEGER NOT NULL,
    navn TEXT,
    PRIMARY KEY (operatørID AUTOINCREMENT)
);

CREATE TABLE Togrute (
    ruteID INTEGER NOT NULL,
    operatørID INTEGER NOT NULL,
    strekningID INTEGER NOT NULL,
    PRIMARY KEY (ruteID AUTOINCREMENT),
    FOREIGN KEY (operatørID) REFERENCES Operatør(operatørID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (strekningID) REFERENCES Banestrekning(strekningID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Ukedag (
    navn TEXT NOT NULL,
    PRIMARY KEY (navn)
);

CREATE TABLE KjørerPåDag (
    ukedag TEXT NOT NULL,
    ruteID INTEGER NOT NULL,
    PRIMARY KEY (ukedag, ruteID),
    FOREIGN KEY (ukedag) REFERENCES Ukedag(navn) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (ruteID) REFERENCES Togrute(ruteID) ON UPDATE CASCADE ON DELETE RESTRICT
    
);

CREATE TABLE TogruteForekomst (
    dato TEXT NOT NULL,
    ruteID INTEGER NOT NULL,
    PRIMARY KEY (dato, ruteID),
    FOREIGN KEY (ruteID) REFERENCES Togrute(ruteID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Rutetabell (
    ruteID INTEGER NOT NULL,
    stasjonNavn TEXT NOT NULL,
    ankomst TEXT,
    avreise TEXT,
    neste_dag BOOLEAN,
    PRIMARY KEY (ruteID, stasjonNavn),
    FOREIGN KEY (ruteID) REFERENCES Togrute(ruteID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (stasjonNavn) REFERENCES Stasjon(navn) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Vogn (
    vognID INTEGER NOT NULL,
    typeID INTEGER NOT NULL,
    PRIMARY KEY (vognID AUTOINCREMENT),
    FOREIGN KEY (typeID) REFERENCES Vogntype(typeID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Vogntype (
    typeID INTEGER NOT NULL,
    navn TEXT,
    operatørID INTEGER NOT NULL,
    PRIMARY KEY (typeID AUTOINCREMENT)
    FOREIGN KEY (operatørID) REFERENCES Operatør(operatørID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE VognOppsett (
    ruteID INTEGER NOT NULL,
    vognID INTEGER NOT NULL,
    vognnummer INTEGER,
    PRIMARY KEY (ruteID, vognID),
    FOREIGN KEY (ruteID) REFERENCES Togrute(ruteID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (vognID) REFERENCES Vogn(vognID) ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE Sovevogn (
  typeID INTEGER NOT NULL,
  antallKupeer INTEGER NOT NULL,
  PRIMARY KEY (typeID),
  FOREIGN KEY (typeID) REFERENCES Vogntype(typeID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Sittevogn (
  typeID INTEGER NOT NULL,
  seteRader INTEGER NOT NULL,
  seteKolonner INTEGER NOT NULL,
  PRIMARY KEY (typeID),
  FOREIGN KEY (typeID) REFERENCES Vogntype(typeID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Sete (
  vognID INTEGER NOT NULL,
  setenummer INTEGER NOT NULL,
  PRIMARY KEY (vognID, setenummer),
  FOREIGN KEY (vognID) REFERENCES Vogn(vognID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Kupee (
  vognID INTEGER NOT NULL,
  kupeenummer INTEGER NOT NULL,
  PRIMARY KEY (vognID, kupeenummer),
  FOREIGN KEY (vognID) REFERENCES Vogn(vognID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Kunde (
  kundenummer INTEGER NOT NULL,
  navn TEXT,
  epost TEXT,
  mobilnummer TEXT,
  PRIMARY KEY (kundenummer AUTOINCREMENT)
);

CREATE TABLE Ordre (
  ordrenummer INTEGER NOT NULL,
  kundenummer INTEGER NOT NULL,
  ordredato TEXT,
  ordretid TEXT,
  PRIMARY KEY (ordrenummer AUTOINCREMENT),
  FOREIGN KEY (kundenummer) REFERENCES Kunde(kundenummer) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE Billett (
  billettID INTEGER NOT NULL,
  start TEXT NOT NULL,
  ende TEXT NOT NULL,
  ordrenummer INTEGER NOT NULL,
  ruteID INTEGER NOT NULL,
  dato TEXT NOT NULL,
  PRIMARY KEY(billettID AUTOINCREMENT),
  FOREIGN KEY(ordrenummer) REFERENCES Ordre(ordrenummer) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(ende) REFERENCES Stasjon(navn) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY(start) REFERENCES Stasjon(navn) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY(ruteID,dato) REFERENCES TogruteForekomst(ruteID,dato) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE SitteBillett (
  billettID INTEGER NOT NULL,
  vognID INTEGER NOT NULL,
  setenummer INTEGER NOT NULL,
  PRIMARY KEY (billettID),
  FOREIGN KEY (vognID, setenummer) REFERENCES Sete(vognID, setenummer) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SoveBillett (
  billettID INTEGER NOT NULL,
  vognID INTEGER NOT NULL,
  kupeenummer INTEGER NOT NULL,
  PRIMARY KEY (billettID),
  FOREIGN KEY (vognID, kupeenummer) REFERENCES Kupee(vognID, kupeenummer) ON UPDATE CASCADE ON DELETE CASCADE
);
